#!/bin/bash
#PBS -l nodes=1:ppn=6
#PBS -l walltime=04:00:00
#PBS -N outpbexNUMx
#PBS -q spst_pub
#PBS -j oe

set -eo pipefail
source /public/software/compiler/intel/composer_xe_2019.1.022/7/compilers_and_libraries_2019.3.199/linux/bin/compilervars.sh intel64 #SHTU
source /public/software/compiler/intel/composer_xe_2019.1.022/7/compilers_and_libraries_2019.3.199/linux/mpi/intel64/bin/mpivars.sh #SHTU

cd $PBS_O_WORKDIR
cp $PBS_NODEFILE node
NP=`wc -l < $PBS_NODEFILE`
SECONDS=0

PW=~/tianff/201903/tianff/software/epsilon0_1.8+alpha0_2.14_GW-lf-fq-cori-ice/bin/pw.x

echo $PW
echo $NP

mpirun -np $NP $PW < scf.in > scf.out

nodeinfo=($(sort -n node | uniq))
echo "TotalTime $((${SECONDS} / 60)) m $((${SECONDS} % 60)) s; CoreNum ${NP}; CoreInfo ${nodeinfo[*]}."

