#!/bin/bash
set -euo pipefail

FeffPath=/home/faye/software/feff10/bin/MPI
if [ $# = 0 ]; then
    MPICOMMAND="mpirun "
else
    MPICOMMAND="mpirun -np $1 "
fi
$MPICOMMAND $FeffPath/rdinp
exit
$MPICOMMAND $FeffPath/atomic
$MPICOMMAND $FeffPath/dmdw
$MPICOMMAND $FeffPath/opconsat
$MPICOMMAND $FeffPath/pot
$MPICOMMAND $FeffPath/ldos
$MPICOMMAND $FeffPath/screen
$MPICOMMAND $FeffPath/xsph
$MPICOMMAND $FeffPath/fms
$MPICOMMAND $FeffPath/mkgtr
$MPICOMMAND $FeffPath/path
$MPICOMMAND $FeffPath/genfmt
$MPICOMMAND $FeffPath/ff2x
$MPICOMMAND $FeffPath/sfconv
$MPICOMMAND $FeffPath/compton
$MPICOMMAND $FeffPath/eels
$MPICOMMAND $FeffPath/rhorrp
