#! /bin/bash
#PBS -l nodes=15:ppn=36
#PBS -N outgwxNUMx
#PBS -q sbp_1
#PBS -j oe

set -eo pipefail
source ~/tianff/environment.sh
SECONDS=0

cd $PBS_O_WORKDIR
cp $PBS_NODEFILE node
NP=`cat node | wc -l`
NP=512

CP=~/tianff/201903/tianff/software/GW-lf-fq-cori-ice_epsilon0_3.0+alpha_2.3/bin/cp.x

echo $CP
echo $NP

mpirun -np $NP $CP < gw.in > gw.out

nodeinfo=($(sort -n node | uniq))
echo "TotalTime $((${SECONDS} / 60)) m $((${SECONDS} % 60)) s; CoreNum ${NP}; CoreInfo ${nodeinfo[*]}."
