#!/bin/bash
set -eo pipefail

#rm -rf cp_lambda.dat
#rm -rf cp-nscf.in
#rm -rf cp-nscf.out
#rm -rf cp-nscf-wf.in
#rm -rf cp-nscf-wf.out
#rm -rf cp-scf.in
#rm -rf cp-scf.out
#rm -rf cp_wf.dat
rm -rf diag_lambda.dat
rm -rf eigc.dat
rm -rf eig.dat
#rm -rf fort.10
#rm -rf fort.11
#rm -rf fort.12
#rm -rf fort.13
rm -rf fort.20
rm -rf fort.407
rm -rf fort.408
#rm -rf fort.777
rm -rf g.dat
#rm -rf gw.in
#rm -rf gw.out
#rm -rf gw.sh
rm -rf node
#rm -rf nscf.in
#rm -rf nscf.out
#rm -rf OO_pos_1.dat
#rm -rf outgw1.o710876
#rm -rf outpbe1.o710843
#rm -rf outxas1.o711101
#rm -rf pbe.sh
#rm -rf scf.in
#rm -rf scf.out
rm -rf temp
#rm -rf tm.dat
#rm -rf tmsftbroad.dat
#rm -rf tmsft.dat
#rm -rf xas.out
#rm -rf xas.sh
