#!/bin/bash
source ~/tianff/codes/common/environment.sh
set -euo pipefail

rm -f CHG
rm -f CHGCAR
#rm -f CONTCAR
#rm -f DOSCAR
#rm -f EIGENVAL
#rm -f IBZKPT
#rm -f INCAR
#rm -f KPOINTS
#rm -f OSZICAR
#rm -f OUTCAR
#rm -f PCDAT
#rm -f POSCAR
#rm -f POTCAR
#rm -f PROCAR
#rm -f REPORT
#rm -f slurm-2811361.out
#rm -f vasprun.xml
#rm -f vasp.sbatch
rm -f WAVECAR
#rm -f XDATCAR
#rm -f STOPCAR

rm -f */CHG
rm -f */CHGCAR
#rm -f */CONTCAR
#rm -f */DOSCAR
#rm -f */EIGENVAL
#rm -f */IBZKPT
#rm -f */INCAR
#rm -f */KPOINTS
#rm -f */OSZICAR
#rm -f */OUTCAR
#rm -f */PCDAT
#rm -f */POSCAR
#rm -f */POTCAR
#rm -f */PROCAR
#rm -f */REPORT
#rm -f */slurm-2811361.out
#rm -f */vasprun.xml
#rm -f */vasp.sbatch
rm -f */WAVECAR
#rm -f */XDATCAR
#rm -f */POSCAR.vasp
#rm -f */POSCAR.xyz
#rm -f */fe.dat
