export dir_mdca_code="${homedir}codes/research/202203_MDCarbonicAcid/"
export dir_mdca_work="${homedir}research/202203_MDCarbonicAcid/"
export dir_mdca_shtu="${homedir}research_shtu/202203_MDCarbonicAcid/"
export dir_mdca_d="${homedir}research_d/202203_MDCarbonicAcid/"
export dir_mdca_ms="${homedir}research/202203_MDCarbonicAcid/structure/H2CO3_Files/Documents/"
